// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: IndexMsg.proto

package indexserver_grpc_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName     string `protobuf:"bytes,1,opt,name=EventName,proto3" json:"EventName"`
	EventDateTime string `protobuf:"bytes,2,opt,name=EventDateTime,proto3" json:"EventDateTime"`
	ClientKey     string `protobuf:"bytes,3,opt,name=ClientKey,proto3" json:"ClientKey"`
	UserId        string `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId"`
	Location      string `protobuf:"bytes,5,opt,name=Location,proto3" json:"Location"`
}

func (x *EventLog) Reset() {
	*x = EventLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLog) ProtoMessage() {}

func (x *EventLog) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLog.ProtoReflect.Descriptor instead.
func (*EventLog) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{0}
}

func (x *EventLog) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventLog) GetEventDateTime() string {
	if x != nil {
		return x.EventDateTime
	}
	return ""
}

func (x *EventLog) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *EventLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventLog) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type UserOnLineAndLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId"`
	Location         string `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location"`
	LocationDateTime string `protobuf:"bytes,3,opt,name=LocationDateTime,proto3" json:"LocationDateTime"`
	OnLineDateTime   string `protobuf:"bytes,4,opt,name=OnLineDateTime,proto3" json:"OnLineDateTime"`
}

func (x *UserOnLineAndLocation) Reset() {
	*x = UserOnLineAndLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnLineAndLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnLineAndLocation) ProtoMessage() {}

func (x *UserOnLineAndLocation) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnLineAndLocation.ProtoReflect.Descriptor instead.
func (*UserOnLineAndLocation) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{1}
}

func (x *UserOnLineAndLocation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserOnLineAndLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UserOnLineAndLocation) GetLocationDateTime() string {
	if x != nil {
		return x.LocationDateTime
	}
	return ""
}

func (x *UserOnLineAndLocation) GetOnLineDateTime() string {
	if x != nil {
		return x.OnLineDateTime
	}
	return ""
}

type UserFragment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentId      string `protobuf:"bytes,1,opt,name=FragmentId,proto3" json:"FragmentId"`
	UserId          string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId"`
	Location        string `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location"`
	PublishDateTime string `protobuf:"bytes,4,opt,name=PublishDateTime,proto3" json:"PublishDateTime"`
}

func (x *UserFragment) Reset() {
	*x = UserFragment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFragment) ProtoMessage() {}

func (x *UserFragment) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFragment.ProtoReflect.Descriptor instead.
func (*UserFragment) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{2}
}

func (x *UserFragment) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

func (x *UserFragment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFragment) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UserFragment) GetPublishDateTime() string {
	if x != nil {
		return x.PublishDateTime
	}
	return ""
}

type AddEventLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName     string `protobuf:"bytes,1,opt,name=EventName,proto3" json:"EventName"`
	EventDateTime string `protobuf:"bytes,2,opt,name=EventDateTime,proto3" json:"EventDateTime"`
	ClientKey     string `protobuf:"bytes,3,opt,name=ClientKey,proto3" json:"ClientKey"`
	UserId        string `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId"`
	Lat           string `protobuf:"bytes,5,opt,name=Lat,proto3" json:"Lat"`
	Lon           string `protobuf:"bytes,6,opt,name=Lon,proto3" json:"Lon"`
}

func (x *AddEventLogRequest) Reset() {
	*x = AddEventLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEventLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventLogRequest) ProtoMessage() {}

func (x *AddEventLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventLogRequest.ProtoReflect.Descriptor instead.
func (*AddEventLogRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{3}
}

func (x *AddEventLogRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *AddEventLogRequest) GetEventDateTime() string {
	if x != nil {
		return x.EventDateTime
	}
	return ""
}

func (x *AddEventLogRequest) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *AddEventLogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddEventLogRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *AddEventLogRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

type SaveOrUpdateUserOnLineAndLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId"`
	Lat              string `protobuf:"bytes,2,opt,name=Lat,proto3" json:"Lat"`
	Lon              string `protobuf:"bytes,3,opt,name=Lon,proto3" json:"Lon"`
	LocationDateTime string `protobuf:"bytes,4,opt,name=LocationDateTime,proto3" json:"LocationDateTime"`
	OnLineDateTime   string `protobuf:"bytes,5,opt,name=OnLineDateTime,proto3" json:"OnLineDateTime"`
}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) Reset() {
	*x = SaveOrUpdateUserOnLineAndLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateUserOnLineAndLocationRequest) ProtoMessage() {}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateUserOnLineAndLocationRequest.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateUserOnLineAndLocationRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{4}
}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) GetLocationDateTime() string {
	if x != nil {
		return x.LocationDateTime
	}
	return ""
}

func (x *SaveOrUpdateUserOnLineAndLocationRequest) GetOnLineDateTime() string {
	if x != nil {
		return x.OnLineDateTime
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId"`
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddUserFragmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentId      string `protobuf:"bytes,1,opt,name=FragmentId,proto3" json:"FragmentId"`
	UserId          string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId"`
	Lat             string `protobuf:"bytes,3,opt,name=Lat,proto3" json:"Lat"`
	Lon             string `protobuf:"bytes,4,opt,name=Lon,proto3" json:"Lon"`
	PublishDateTime string `protobuf:"bytes,5,opt,name=PublishDateTime,proto3" json:"PublishDateTime"`
}

func (x *AddUserFragmentRequest) Reset() {
	*x = AddUserFragmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUserFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserFragmentRequest) ProtoMessage() {}

func (x *AddUserFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserFragmentRequest.ProtoReflect.Descriptor instead.
func (*AddUserFragmentRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{6}
}

func (x *AddUserFragmentRequest) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

func (x *AddUserFragmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserFragmentRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *AddUserFragmentRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *AddUserFragmentRequest) GetPublishDateTime() string {
	if x != nil {
		return x.PublishDateTime
	}
	return ""
}

type DeleteFragmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FragmentId string `protobuf:"bytes,1,opt,name=FragmentId,proto3" json:"FragmentId"`
}

func (x *DeleteFragmentRequest) Reset() {
	*x = DeleteFragmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFragmentRequest) ProtoMessage() {}

func (x *DeleteFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFragmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteFragmentRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFragmentRequest) GetFragmentId() string {
	if x != nil {
		return x.FragmentId
	}
	return ""
}

type QueryNearbyPersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat                 string   `protobuf:"bytes,1,opt,name=Lat,proto3" json:"Lat"`
	Lon                 string   `protobuf:"bytes,2,opt,name=Lon,proto3" json:"Lon"`
	UserIds             []string `protobuf:"bytes,3,rep,name=UserIds,proto3" json:"UserIds"`
	AfterOnlineDateTime string   `protobuf:"bytes,4,opt,name=AfterOnlineDateTime,proto3" json:"AfterOnlineDateTime"`
	Start               int32    `protobuf:"varint,5,opt,name=Start,proto3" json:"Start"`
	Limit               int32    `protobuf:"varint,6,opt,name=Limit,proto3" json:"Limit"`
	InnerDistance       int64    `protobuf:"varint,7,opt,name=InnerDistance,proto3" json:"InnerDistance"`
}

func (x *QueryNearbyPersonRequest) Reset() {
	*x = QueryNearbyPersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNearbyPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNearbyPersonRequest) ProtoMessage() {}

func (x *QueryNearbyPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNearbyPersonRequest.ProtoReflect.Descriptor instead.
func (*QueryNearbyPersonRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{8}
}

func (x *QueryNearbyPersonRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *QueryNearbyPersonRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *QueryNearbyPersonRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *QueryNearbyPersonRequest) GetAfterOnlineDateTime() string {
	if x != nil {
		return x.AfterOnlineDateTime
	}
	return ""
}

func (x *QueryNearbyPersonRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *QueryNearbyPersonRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryNearbyPersonRequest) GetInnerDistance() int64 {
	if x != nil {
		return x.InnerDistance
	}
	return 0
}

type QueryNearbyFragmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat                  string   `protobuf:"bytes,1,opt,name=Lat,proto3" json:"Lat"`
	Lon                  string   `protobuf:"bytes,2,opt,name=Lon,proto3" json:"Lon"`
	UserIds              []string `protobuf:"bytes,3,rep,name=UserIds,proto3" json:"UserIds"`
	AfterPublishDateTime string   `protobuf:"bytes,4,opt,name=AfterPublishDateTime,proto3" json:"AfterPublishDateTime"`
	Start                int32    `protobuf:"varint,5,opt,name=Start,proto3" json:"Start"`
	Limit                int32    `protobuf:"varint,6,opt,name=Limit,proto3" json:"Limit"`
	InnerDistance        int64    `protobuf:"varint,7,opt,name=InnerDistance,proto3" json:"InnerDistance"`
}

func (x *QueryNearbyFragmentRequest) Reset() {
	*x = QueryNearbyFragmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNearbyFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNearbyFragmentRequest) ProtoMessage() {}

func (x *QueryNearbyFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNearbyFragmentRequest.ProtoReflect.Descriptor instead.
func (*QueryNearbyFragmentRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{9}
}

func (x *QueryNearbyFragmentRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *QueryNearbyFragmentRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *QueryNearbyFragmentRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *QueryNearbyFragmentRequest) GetAfterPublishDateTime() string {
	if x != nil {
		return x.AfterPublishDateTime
	}
	return ""
}

func (x *QueryNearbyFragmentRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *QueryNearbyFragmentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryNearbyFragmentRequest) GetInnerDistance() int64 {
	if x != nil {
		return x.InnerDistance
	}
	return 0
}

type QueryEventLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName    string `protobuf:"bytes,1,opt,name=EventName,proto3" json:"EventName"`
	FromDateTime string `protobuf:"bytes,2,opt,name=FromDateTime,proto3" json:"FromDateTime"`
	EndDateTime  string `protobuf:"bytes,3,opt,name=EndDateTime,proto3" json:"EndDateTime"`
	Start        int32  `protobuf:"varint,4,opt,name=Start,proto3" json:"Start"`
	Limit        int32  `protobuf:"varint,5,opt,name=Limit,proto3" json:"Limit"`
}

func (x *QueryEventLogRequest) Reset() {
	*x = QueryEventLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEventLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventLogRequest) ProtoMessage() {}

func (x *QueryEventLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventLogRequest.ProtoReflect.Descriptor instead.
func (*QueryEventLogRequest) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{10}
}

func (x *QueryEventLogRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *QueryEventLogRequest) GetFromDateTime() string {
	if x != nil {
		return x.FromDateTime
	}
	return ""
}

func (x *QueryEventLogRequest) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

func (x *QueryEventLogRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *QueryEventLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OperResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
}

func (x *OperResponse) Reset() {
	*x = OperResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperResponse) ProtoMessage() {}

func (x *OperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperResponse.ProtoReflect.Descriptor instead.
func (*OperResponse) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{11}
}

func (x *OperResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchEventLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code"`
	Message string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
	Data    []*EventLog `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data"`
}

func (x *SearchEventLogResponse) Reset() {
	*x = SearchEventLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEventLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventLogResponse) ProtoMessage() {}

func (x *SearchEventLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventLogResponse.ProtoReflect.Descriptor instead.
func (*SearchEventLogResponse) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{12}
}

func (x *SearchEventLogResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchEventLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchEventLogResponse) GetData() []*EventLog {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchUserOnLineAndLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code"`
	Message string                   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
	Data    []*UserOnLineAndLocation `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data"`
}

func (x *SearchUserOnLineAndLocationResponse) Reset() {
	*x = SearchUserOnLineAndLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserOnLineAndLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserOnLineAndLocationResponse) ProtoMessage() {}

func (x *SearchUserOnLineAndLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserOnLineAndLocationResponse.ProtoReflect.Descriptor instead.
func (*SearchUserOnLineAndLocationResponse) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{13}
}

func (x *SearchUserOnLineAndLocationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchUserOnLineAndLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchUserOnLineAndLocationResponse) GetData() []*UserOnLineAndLocation {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchUserFragmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32           `protobuf:"varint,1,opt,name=Code,proto3" json:"Code"`
	Message string          `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
	Data    []*UserFragment `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data"`
}

func (x *SearchUserFragmentResponse) Reset() {
	*x = SearchUserFragmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IndexMsg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserFragmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserFragmentResponse) ProtoMessage() {}

func (x *SearchUserFragmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IndexMsg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserFragmentResponse.ProtoReflect.Descriptor instead.
func (*SearchUserFragmentResponse) Descriptor() ([]byte, []int) {
	return file_IndexMsg_proto_rawDescGZIP(), []int{14}
}

func (x *SearchUserFragmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchUserFragmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchUserFragmentResponse) GetData() []*UserFragment {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_IndexMsg_proto protoreflect.FileDescriptor

var file_IndexMsg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e,
	0x4c, 0x69, 0x6e, 0x65, 0x41, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f, 0x6e, 0x22, 0xba, 0x01, 0x0a, 0x28,
	0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x41, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c,
	0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4c, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x9e, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0xdc, 0x01, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x4c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x4c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x41, 0x66,
	0x74, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x41, 0x66, 0x74, 0x65, 0x72, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0xe0,
	0x01, 0x0a, 0x1a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x46, 0x72,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x4c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x41,
	0x66, 0x74, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x41, 0x66, 0x74, 0x65, 0x72,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x49,
	0x6e, 0x6e, 0x65, 0x72, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x72, 0x6f, 0x6d,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x46, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3c, 0x0a, 0x0c, 0x4f, 0x70,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x76, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x90, 0x01, 0x0a, 0x23, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x41, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x4c, 0x69,
	0x6e, 0x65, 0x41, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x7e, 0x0a, 0x1a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x32, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_IndexMsg_proto_rawDescOnce sync.Once
	file_IndexMsg_proto_rawDescData = file_IndexMsg_proto_rawDesc
)

func file_IndexMsg_proto_rawDescGZIP() []byte {
	file_IndexMsg_proto_rawDescOnce.Do(func() {
		file_IndexMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_IndexMsg_proto_rawDescData)
	})
	return file_IndexMsg_proto_rawDescData
}

var file_IndexMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_IndexMsg_proto_goTypes = []interface{}{
	(*EventLog)(nil),                                 // 0: indexserver_grpc.EventLog
	(*UserOnLineAndLocation)(nil),                    // 1: indexserver_grpc.UserOnLineAndLocation
	(*UserFragment)(nil),                             // 2: indexserver_grpc.UserFragment
	(*AddEventLogRequest)(nil),                       // 3: indexserver_grpc.AddEventLogRequest
	(*SaveOrUpdateUserOnLineAndLocationRequest)(nil), // 4: indexserver_grpc.SaveOrUpdateUserOnLineAndLocationRequest
	(*DeleteUserRequest)(nil),                        // 5: indexserver_grpc.DeleteUserRequest
	(*AddUserFragmentRequest)(nil),                   // 6: indexserver_grpc.AddUserFragmentRequest
	(*DeleteFragmentRequest)(nil),                    // 7: indexserver_grpc.DeleteFragmentRequest
	(*QueryNearbyPersonRequest)(nil),                 // 8: indexserver_grpc.QueryNearbyPersonRequest
	(*QueryNearbyFragmentRequest)(nil),               // 9: indexserver_grpc.QueryNearbyFragmentRequest
	(*QueryEventLogRequest)(nil),                     // 10: indexserver_grpc.QueryEventLogRequest
	(*OperResponse)(nil),                             // 11: indexserver_grpc.OperResponse
	(*SearchEventLogResponse)(nil),                   // 12: indexserver_grpc.SearchEventLogResponse
	(*SearchUserOnLineAndLocationResponse)(nil),      // 13: indexserver_grpc.SearchUserOnLineAndLocationResponse
	(*SearchUserFragmentResponse)(nil),               // 14: indexserver_grpc.SearchUserFragmentResponse
}
var file_IndexMsg_proto_depIdxs = []int32{
	0, // 0: indexserver_grpc.SearchEventLogResponse.Data:type_name -> indexserver_grpc.EventLog
	1, // 1: indexserver_grpc.SearchUserOnLineAndLocationResponse.Data:type_name -> indexserver_grpc.UserOnLineAndLocation
	2, // 2: indexserver_grpc.SearchUserFragmentResponse.Data:type_name -> indexserver_grpc.UserFragment
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_IndexMsg_proto_init() }
func file_IndexMsg_proto_init() {
	if File_IndexMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_IndexMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnLineAndLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFragment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEventLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateUserOnLineAndLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUserFragmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFragmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNearbyPersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNearbyFragmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEventLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchEventLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchUserOnLineAndLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IndexMsg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchUserFragmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_IndexMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IndexMsg_proto_goTypes,
		DependencyIndexes: file_IndexMsg_proto_depIdxs,
		MessageInfos:      file_IndexMsg_proto_msgTypes,
	}.Build()
	File_IndexMsg_proto = out.File
	file_IndexMsg_proto_rawDesc = nil
	file_IndexMsg_proto_goTypes = nil
	file_IndexMsg_proto_depIdxs = nil
}
